# Generated by Django 5.0.6 on 2024-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Node',
            new_name='node',
        ),
        migrations.AlterField(
            model_name='networknode',
            name='type',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('entrepreneur', 'ИП')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
