# Generated by Django 5.0.6 on 2024-07-09 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0002_rename_node_product_node_alter_networknode_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='node',
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SupplierNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('factory', 'Завод'), ('entrepreneur', 'ИП'), ('retail_network', 'Розничная сеть')], max_length=30, verbose_name='Тип структуры')),
                ('debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('hierarchy_level', models.IntegerField(blank=True, verbose_name='Уровень в иерархии')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_network.contacts', verbose_name='Контакты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Поставщик', to='electronic_network.suppliernode')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
            },
        ),
        migrations.DeleteModel(
            name='NetworkNode',
        ),
        migrations.AddField(
            model_name='product',
            name='node',
            field=models.ManyToManyField(related_name='Сеть', to='electronic_network.suppliernode'),
        ),
    ]
