# Generated by Django 5.0.6 on 2024-07-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0003_contacts_remove_product_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliernode',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contacts',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronic_network.suppliernode', verbose_name='Поставщик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='hierarchy_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень в иерархии'),
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='type',
            field=models.CharField(choices=[('entrepreneur', 'ИП'), ('retail_network', 'Розничная сеть'), ('factory', 'Завод')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
