# Generated by Django 5.0.6 on 2024-07-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0004_remove_suppliernode_contacts_contacts_node_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliernode',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщиков'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='node',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='products', to='electronic_network.suppliernode', verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='electronic_network.suppliernode', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='hierarchy_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень иерархии'),
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronic_network.suppliernode', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='type',
            field=models.CharField(choices=[('factory', 'Завод'), ('entrepreneur', 'ИП'), ('retail_network', 'Розничная сеть')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
