# Generated by Django 5.0.6 on 2024-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0005_alter_suppliernode_options_remove_product_node_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='node',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='type',
            field=models.CharField(choices=[('retail_network', 'Розничная сеть'), ('entrepreneur', 'ИП'), ('factory', 'Завод')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
