# Generated by Django 5.0.6 on 2024-07-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0006_rename_node_contacts_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliernode',
            name='type',
            field=models.CharField(choices=[('retail_network', 'Розничная сеть'), ('factory', 'Завод'), ('entrepreneur', 'ИП')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
