# Generated by Django 5.0.6 on 2024-07-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0008_alter_suppliernode_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliernode',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='suppliernode',
            name='type',
            field=models.CharField(choices=[('retail_network', 'Розничная сеть'), ('entrepreneur', 'ИП'), ('factory', 'Завод')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
