# Generated by Django 5.0.6 on 2024-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0009_alter_suppliernode_options_alter_suppliernode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliernode',
            name='type',
            field=models.CharField(choices=[('retail_network', 'Розничная сеть'), ('factory', 'Завод'), ('entrepreneur', 'ИП')], max_length=30, verbose_name='Тип структуры'),
        ),
    ]
